### ISSUE TITLE
normalize fft'd image

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/rfgpu#1]
I don't recall the standard normalization for an FFT, but it would help to do it by default. Currently, adding a 1 Jy source gives a peak of 1.4e5.

**Comment by demorest** [comment]
There is not really a standard normalization AFAIK.  Some of the common choices would be to divide by either the total number of pixels, or the sqrt of number of pixels.  How is this handled in rfpipe?  I took a quick look through the code and didn't see any particular normalization applied..

**Comment by demorest** [comment]
Just experimenting with this a bit, it looks like the thing to do might be normalize the number of visibilities (ie, `2*nbl*nchan`) rather than the number of pixels.  This makes the image peak value correspond to the amplitude of the visibilities.. does that sound right to you?

**Comment by demorest** [comment]
This was a one-line change so I went ahead and did it. Let me know if you think it needs more thought though.

**Comment by caseyjlaw** [comment]
That seems fine. Looking back at my code, I confirmed that in fact I don't take special consideration of normalization. My mistake.
