### ISSUE TITLE
support non-square images

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/rfgpu#3]
Generally, images can have dimension of npixx by npixy. GPU code currently assumes square images.

**Comment by demorest** [comment]
This is actually already supported.  When setting up the image, do: `image = rfgpu.Image(npixx,npixy)`.  I haven't tested any non-square images yet though.  I can update the example script to try this.

**Comment by demorest** [comment]
Ok, I just updated `rfgpu_example.py` to show non-square case.  A super-quick test seems to work OK so I'll close this for now, but re-open if you see any problems!
