### ISSUE TITLE
Support polarization data and Stokes I gridding

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/rfgpu#4]
Current CPU code will assume two circular polarizations and will grid them to the same uv cell. The GPUArrayComplex class needs a polarization axis and gridding would need to iterate over the polarization axis. Probably fine to assume two, orthogonal pols.

**Comment by demorest** [comment]
If the RR and LL pols are always going to be gridded into the same cell, I think it should be equivalent to just sum along the poln axis prior to gridding, right?  I guess I was assuming it would make more sense to do this prior to sending the data to the GPU (mainly to reduce GPU memory usage).

**Comment by caseyjlaw** [comment]
Good point. I'm using this now and things seem to make sense.
