### ISSUE TITLE
warn or drop data that falls outside of uv grid

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/rfgpu#7]
I've compared my cpu grid+image algorithm to rfgpu and found a difference when the grid size is smaller than the uv coverage. That is, instead of gridding all of A config, I'd like to define a 2048x2048 grid and image that subset. The rfgpu version finds no candidates, while the cpu version finds very strong simulated transients (SNR of several hundred).
I'm guessing it is because data that fall outside the grid are wrapped in a modulo npixx/npixy call. What do you think?
I'll sanitize my data before making calling rfgpu, but wanted to raise the issue.

**Comment by demorest** [comment]
rfgpu should already be dropping data that falls outside the range of the UV grid (see grid.cu line 136).  I tested this feature a bit while working on the code and it seemed to be doing the right thing, but there could always be bugs.  Let me know if you find out more about this issue!

**Comment by caseyjlaw** [comment]
Ok, good to know. I also tested this by shrinking the antenna positions in my metadata. It did not fix the issue, which is consistent with what you've done.
I'll keep looking.

**Comment by caseyjlaw** [comment]
A bit more work reveals that rfpipe is not parsing frequency/spw metadata well for some SDMs. I've opened an issue on my end, so I'll close this.
