### ISSUE TITLE
release Python GIL

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/rfgpu#8]
The realfast job scheduler is having some trouble managing workers that hold the GIL for a long time. The GIL gets held by the rfgpu because it is running a for loop like:
```
for dm in dmarr:
    for dt in dtarr:
        for i in integrations:
            ...downsample, dedisperse...
             grid.operate(vis_raw, vis_grid, i)
             image.operate(vis_grid, img_grid)
```
The grid and image operate methods are probably holding the GIL. The for loops may be too.
I have a few options for avoiding the GIL lock in for loops by compiling in cython or numba. However, it may be a simple change in pybind11 on the operate methods. I don't know it well, but does this look like a change that could be implemented in rfgpu.C?
http://pybind11.readthedocs.io/en/master/advanced/misc.html#global-interpreter-lock-gil

**Comment by demorest** [comment]
Yes it looks like it would be easy to have the `operate` methods release the GIL.  I'll go ahead and put this in and we can see what happens..

**Comment by demorest** [comment]
OK this is in now.  I tried the example script and it still seems to work correctly.  Let me know if you see any problems with it..

**Comment by caseyjlaw** [comment]
Works like a charm! Thanks!
