### ISSUE TITLE
image on-gpu stats differ from python image stats

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/rfgpu#9]
I am having trouble finding simulated transients in some cases. I suspect I am giving the search pipeline some bad metadata, but can't pin it down.
In this exploration, I've found that there are cases where the on-gpu image statistics do not agree with what I can get if I pull the image back to the host. E.g.,
```
> stats = image.stats(img_grid)
> peak_snr = stats['max']/stats['rms']
> img_grid.d2h()
> print(peak_snr, img_grid.max()/img_grid.std())
2.242361769789672e-151 101.81512451171875
```

It looks like the on-gpu stats are uninitialized. That may be my fault (my metadata bad?) but I would have assumed that it would at least match the statistics of the img_grid object.
Am I missing something?

**Comment by demorest** [comment]
Is this still happening?  If so is there any way to reliably make it happen?  I have not seen anything like this in my testing.

**Comment by caseyjlaw** [comment]
I have not seen this recently. Could be user error.
We can close it, if you like.
